"""Intercambio SPICE básico para los elementos analógicos de Kirho."""
from __future__ import annotations

from dataclasses import dataclass
import re
from typing import Iterable


@dataclass(frozen=True)
class SpiceElement:
    name: str
    kind: str
    node1: str
    node2: str
    value: float = 0.0
    phase_deg: float = 0.0


@dataclass(frozen=True)
class SpiceParseResult:
    elements: list[SpiceElement]
    warnings: list[str]


_NUMBER = re.compile(r"^([+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?)([a-z]+)?$", re.I)
_SUFFIXES = {
    "t": 1e12, "g": 1e9, "meg": 1e6, "k": 1e3,
    "m": 1e-3, "u": 1e-6, "n": 1e-9, "p": 1e-12, "f": 1e-15,
}


def parse_value(token: str) -> float:
    """Lee números SPICE, incluidos sufijos como ``10k`` y ``4.7uF``."""
    match = _NUMBER.match(token.strip())
    if not match:
        raise ValueError(f"invalid SPICE value: {token}")
    number, suffix = match.groups()
    suffix = (suffix or "").lower()
    multiplier = _SUFFIXES.get("meg" if suffix.startswith("meg") else suffix[:1], 1.0)
    return float(number) * multiplier


def format_value(value: float) -> str:
    """Da formato compacto y compatible con SPICE, sin usar ``M`` ambiguo."""
    value = float(value)
    for threshold, suffix, divisor in (
        (1e12, "T", 1e12), (1e9, "G", 1e9), (1e6, "Meg", 1e6),
        (1e3, "k", 1e3), (1.0, "", 1.0), (1e-3, "m", 1e-3),
        (1e-6, "u", 1e-6), (1e-9, "n", 1e-9), (1e-12, "p", 1e-12),
    ):
        if abs(value) >= threshold:
            return f"{value / divisor:.9g}{suffix}"
    return f"{value:.9g}"


def parse_netlist(text: str) -> SpiceParseResult:
    """Parsea R/C/L/V/I/D de un netlist SPICE convencional.

    # ponytail: sólo primitives de dos terminales; añadir subcircuitos y
    # expresiones cuando exista un caso de importación concreto que lo requiera.
    """
    elements: list[SpiceElement] = []
    warnings: list[str] = []
    saw_title = False
    for line_number, raw_line in enumerate(text.splitlines(), 1):
        line = raw_line.strip()
        if not line or line.startswith("*") or line.startswith(";"):
            continue
        fields = line.split()
        head = fields[0].lower()
        if head.startswith("."):
            continue
        kind = head[0].upper()
        if kind not in {"R", "C", "L", "V", "I", "D"} or len(fields) < 3:
            if not saw_title:
                saw_title = True
                continue
            warnings.append(f"Line {line_number}: unsupported statement ignored")
            continue
        saw_title = True
        if len(fields) < 4:
            warnings.append(f"Line {line_number}: missing value")
            continue
        try:
            value_index = 3
            phase = 0.0
            lower_fields = [field.lower() for field in fields]
            ac_index = next((index for index, field in enumerate(lower_fields[3:], 3)
                             if field == "ac"), None)
            if kind == "V" and ac_index is not None:
                value_index = ac_index + 1
                kind = "VAC"
                phase = parse_value(fields[value_index + 1]) if len(fields) > value_index + 1 else 0.0
            elif kind in {"V", "I"} and fields[3].lower() == "dc":
                value_index = 4
            value = 0.0 if kind == "D" else parse_value(fields[value_index])
        except (IndexError, ValueError) as exc:
            warnings.append(f"Line {line_number}: {exc}")
            continue
        elements.append(SpiceElement(fields[0], kind, fields[1], fields[2], value, phase))
    return SpiceParseResult(elements, warnings)


def export_netlist(components: Iterable, pin_node: dict[str, str], title: str) -> tuple[str, list[str]]:
    """Exporta los primitives compatibles usando nodos reales de la escena."""
    lines = [f"* {title}", "* Generated by Kirho", ""]
    warnings: list[str] = []
    has_diode = False
    type_map = {"R": "R", "C": "C", "L": "L", "V": "V", "VAC": "V", "I": "I"}
    for item in components:
        kind = type_map.get(item.comp_type)
        if item.comp_type in {"D", "LED"}:
            n1 = item.node1.strip() or pin_node.get(f"{item.name}__p1", "")
            n2 = item.node2.strip() or pin_node.get(f"{item.name}__p2", "")
            if not n1 or not n2:
                warnings.append(f"{item.name}: missing node")
                continue
            lines.append(f"D{item.name.lstrip('D')} {n1} {n2} D_KIRHO")
            has_diode = True
            continue
        if kind is None:
            if item.comp_type not in {"GND", "NODE", "NET_LABEL_IN", "NET_LABEL_OUT"}:
                warnings.append(f"{item.name}: {item.comp_type} is not exportable to basic SPICE")
            continue
        n1 = item.node1.strip() or pin_node.get(f"{item.name}__p1", "")
        n2 = item.node2.strip() or pin_node.get(f"{item.name}__p2", "")
        if not n1 or not n2:
            warnings.append(f"{item.name}: missing node")
            continue
        if item.comp_type == "VAC":
            lines.append(f"{item.name} {n1} {n2} DC 0 AC {format_value(item.value)} {item.phase_deg:.9g}")
        else:
            lines.append(f"{item.name} {n1} {n2} {format_value(item.value)}")
    if has_diode:
        lines.extend(["", ".model D_KIRHO D(Is=1e-14 N=1)"])
    lines.extend(["", ".op", ".end", ""])
    return "\n".join(lines), warnings
